# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_articles_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='pretext',
            field=models.TextField(max_length=170),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
